Project LMS/Controllers/DanhsachsinhvienController.cs
using Project_LMS.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;



namespace WebApplication5.Controllers
{
    public class DanhsachsinhvienController : Controller
    {
        private LMSEntities db = new LMSEntities();
        // GET: Danhsachsinhvien
        public ActionResult Index(string SearchString = "", string searchGrade = "",
            string searchClass = "", string searchObject = "", string searchStatus = "")
        {
            var dssinhvien = from x in db.Danh_sách_sinh_viên select x;
            if (SearchString != "")
            {
                dssinhvien = dssinhvien.Where(x => x.tenhocvien.Contains(SearchString));
            }
            if (searchClass != "")
            {
                dssinhvien = dssinhvien.Where(x => x.lop.Contains(searchClass));
            }
            if (searchStatus != "")
            {
                dssinhvien = dssinhvien.Where(x => x.trangthai.Contains(searchStatus));
            }
            if (searchGrade != "")
            {
                dssinhvien = dssinhvien.Where(x => x.khoa_khoi.Contains(searchGrade));
            }
            if (searchObject != "")
            {
                dssinhvien = dssinhvien.Where(x => x.doituong.Contains(searchObject));
            }
            return View(dssinhvien.ToList());
        }
        // GET: Danhsachsinhvien/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Danh_sách_sinh_viên danh_sách_sinh_viên = db.Danh_sách_sinh_viên.Find(id);
            if (danh_sách_sinh_viên == null)
            {
                return HttpNotFound();
            }
            return View(danh_sách_sinh_viên);
        }

        // GET: Danhsachsinhvien/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Danhsachsinhvien/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "mahocvien,tenhocvien,lop,khoa_khoi,doituong,sdt,ngaynhaphoc,hocphi,trangthai,thucthu,ngaythu")] Danh_sách_sinh_viên danh_sách_sinh_viên)
        {
            if (ModelState.IsValid)
            {
                db.Danh_sách_sinh_viên.Add(danh_sách_sinh_viên);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(danh_sách_sinh_viên);
        }

        // GET: Danhsachsinhvien/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Danh_sách_sinh_viên danh_sách_sinh_viên = db.Danh_sách_sinh_viên.Find(id);
            if (danh_sách_sinh_viên == null)
            {
                return HttpNotFound();
            }
            return View(danh_sách_sinh_viên);
        }

        // POST: Danhsachsinhvien/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "mahocvien,tenhocvien,lop,khoa_khoi,doituong,sdt,ngaynhaphoc,hocphi,trangthai,thucthu,ngaythu")] Danh_sách_sinh_viên danh_sách_sinh_viên)
        {
            if (ModelState.IsValid)
            {
                db.Entry(danh_sách_sinh_viên).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(danh_sách_sinh_viên);
        }

        // GET: Danhsachsinhvien/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Danh_sách_sinh_viên danh_sách_sinh_viên = db.Danh_sách_sinh_viên.Find(id);
            if (danh_sách_sinh_viên == null)
            {
                return HttpNotFound();
            }
            return View(danh_sách_sinh_viên);
        }

        // POST: Danhsachsinhvien/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Danh_sách_sinh_viên danh_sách_sinh_viên = db.Danh_sách_sinh_viên.Find(id);
            db.Danh_sách_sinh_viên.Remove(danh_sách_sinh_viên);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Status(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Danh_sách_sinh_viên danh_sách_sinh_viên = db.Danh_sách_sinh_viên.Find(id);
            if (danh_sách_sinh_viên == null)
            {
                return HttpNotFound();
            }
            return View(danh_sách_sinh_viên);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Status([Bind(Include = "mahocvien,tenhocvien,lop,khoa_khoi,doituong,sdt,ngaynhaphoc,hocphi,trangthai,thucthu,ngaythu")] Danh_sách_sinh_viên danh_sách_sinh_viên)
        {
            if (ModelState.IsValid)
            {
                db.Entry(danh_sách_sinh_viên).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(danh_sách_sinh_viên);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project LMS/Views/Danhsachsinhvien/Create.cshtml
@model Project_LMS.Models.Danh_sách_sinh_viên

@{
    ViewBag.Title = "Create";
}

<h2>Danh sách sinh viên</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm sinh viên</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.mahocvien, "Mã học viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mahocvien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mahocvien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tenhocvien, "Tên học viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenhocvien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenhocvien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lop, "lớp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.lop, (IEnumerable<SelectListItem>
                   )(new[] {
                    new SelectListItem() { Text = "6A" },
                    new SelectListItem() { Text = "6B" },
                    new SelectListItem() { Text = "6C" },
                    new SelectListItem() { Text = "6D" },
                    new SelectListItem() { Text = "6E" },
                    new SelectListItem() { Text = "6F" },
                    new SelectListItem() { Text = "7A" },
                    new SelectListItem() { Text = "7B" },
                    new SelectListItem() { Text = "7C" },
                    new SelectListItem() { Text = "7D" },
                    new SelectListItem() { Text = "7E" },
                    new SelectListItem() { Text = "7F" },
                    new SelectListItem() { Text = "8A" },
                    new SelectListItem() { Text = "8B" },
                    new SelectListItem() { Text = "8C" },
                    new SelectListItem() { Text = "8D" },
                    new SelectListItem() { Text = "8E" },
                    new SelectListItem() { Text = "8F" },
                    new SelectListItem() { Text = "9A" },
                    new SelectListItem() { Text = "9B" },
                    new SelectListItem() { Text = "9C" },
                    new SelectListItem() { Text = "9D" },
                    new SelectListItem() { Text = "9E" },
                    new SelectListItem() { Text = "9F" },
                   }), "chọn Lớp", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.lop, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.khoa_khoi, "Khoa / Khối", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.khoa_khoi, (IEnumerable<SelectListItem>
                    )(new[] {
                    new SelectListItem() { Text = "Khối 6" },
                    new SelectListItem() { Text = "Khối 7" },
                    new SelectListItem() { Text = "Khối 8" },
                    new SelectListItem() { Text = "Khối 9" },
                    }), "chọn khoa / Khối", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.khoa_khoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.doituong, "Đối tượng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.doituong, (IEnumerable<SelectListItem>
                    )(new[] {
                    new SelectListItem() { Text = "Không" },
                    new SelectListItem() { Text = "10%" },
                    new SelectListItem() { Text = "20%" },
                    new SelectListItem() { Text = "25%" },
                    new SelectListItem() { Text = "30%" },
                    new SelectListItem() { Text = "40%" },
                    new SelectListItem() { Text = "50%" },
                    new SelectListItem() { Text = "60%" },
                    new SelectListItem() { Text = "70%" },
                    new SelectListItem() { Text = "75%" },
                    new SelectListItem() { Text = "80%" },
                    new SelectListItem() { Text = "90%" },
                    new SelectListItem() { Text = "100%" },
                    }), "Chọn đối tượng", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.doituong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sdt, "Số điện thoại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sdt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sdt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngaynhaphoc, "Ngày nhập học", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaynhaphoc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaynhaphoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hocphi, "Học phí", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hocphi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hocphi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.trangthai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.trangthai, (IEnumerable<SelectListItem>
                    )(new[] {
                    new SelectListItem() { Text = "Đã đóng" },
                    new SelectListItem() { Text = "Chưa đóng" },
                    }), "Chọn trạng thái", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.trangthai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.thucthu, "Thực thu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.thucthu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.thucthu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngaythu, "Ngày thu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaythu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaythu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-default" href="~/Danhsachsinhvien/Index" >Quay lại</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project LMS/Views/Danhsachsinhvien/Delete.cshtml
@model Project_LMS.Models.Danh_sách_sinh_viên

@{
    ViewBag.Title = "Delete";
}

<h2>Xóa học viên</h2>

<h3>Bạn có chắc chắn muốn xóa học viên này không?</h3>
<div>
    <h4>Thông tin của học viên</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên học viên:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenhocvien)
        </dd>

        <dt>
            Lớp:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lop)
        </dd>

        <dt>
            Khóa / khối:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.khoa_khoi)
        </dd>

        <dt>
            Đối tượng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doituong)
        </dd>

        <dt>
            Số điện thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sdt)
        </dd>

        <dt>
            Ngày nhập học:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaynhaphoc)
        </dd>

        <dt>
            Học phí:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hocphi)
        </dd>

        <dt>
            Trạng thái:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trangthai)
        </dd>

        <dt>
            Thực thu:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.thucthu)
        </dd>

        <dt>
            Ngày thu:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaythu)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            <a class="btn btn-default" href="~/Danhsachsinhvien/Index">Quay lại</a>
        </div>
    }
</div>

Project LMS/Views/Danhsachsinhvien/Details.cshtml
@model Project_LMS.Models.Danh_sách_sinh_viên

@{
    ViewBag.Title = "Details";
}

<h2>Chi tiết sinh viên</h2>

<div>
    <h4>Thông tin chi tiết</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên học viên:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenhocvien)
        </dd>

        <dt>
            Lớp:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lop)
        </dd>

        <dt>
            Khóa / khối:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.khoa_khoi)
        </dd>

        <dt>
            Đối tượng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doituong)
        </dd>

        <dt>
            Số điện thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sdt)
        </dd>

        <dt>
            Ngày nhập học:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaynhaphoc)
        </dd>

        <dt>
            Học phí:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hocphi)
        </dd>

        <dt>
            Trạng thái:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trangthai)
        </dd>

        <dt>
            Thực thu:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.thucthu)
        </dd>

        <dt>
            Ngày thu:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaythu)
        </dd>

    </dl>
</div>
<p>
    <a class="btn btn-default" @Html.ActionLink("Sửa", "Edit", new { id = Model.mahocvien }) | </a>
    <a class="btn btn-default" href="~/Danhsachsinhvien/Index">Quay lại</a>
</p>

Project LMS/Views/Danhsachsinhvien/Index.cshtml
@model IEnumerable<Project_LMS.Models.Danh_sách_sinh_viên>

@{
    ViewBag.Title = "Index";
}

<h2>Danh sách sinh viên</h2>

<p>
    @Html.ActionLink("Thêm học viên", "Create")
</p>
@using (Html.BeginForm("Index", "Danhsachsinhvien", FormMethod.Post))
{
    <div class="form-group form-inline">
        <input type="text" name="SearchString" placeholder="Nhập tên sinh viên" class="form-control" />
        @Html.DropDownList("SearchGrade", (IEnumerable<SelectListItem>)
               (new[] {
               new SelectListItem(){ Text = "Khối 6" },
               new SelectListItem() { Text = "Khối 7" },
               new SelectListItem() { Text = "Khối 8" },
               new SelectListItem() { Text = "Khối 9" },
               }), "Chọn khoa / khối", new { @class = "form-control" })

        @Html.DropDownList("SearchClass", (IEnumerable<SelectListItem>
                    )(new[] {
                    new SelectListItem() { Text = "6A" },
                    new SelectListItem() { Text = "6B" },
                    new SelectListItem() { Text = "6C" },
                    new SelectListItem() { Text = "6D" },
                    new SelectListItem() { Text = "6E" },
                    new SelectListItem() { Text = "6F" },
                    new SelectListItem() { Text = "7A" },
                    new SelectListItem() { Text = "7B" },
                    new SelectListItem() { Text = "7C" },
                    new SelectListItem() { Text = "7D" },
                    new SelectListItem() { Text = "7E" },
                    new SelectListItem() { Text = "7F" },
                    new SelectListItem() { Text = "8A" },
                    new SelectListItem() { Text = "8B" },
                    new SelectListItem() { Text = "8C" },
                    new SelectListItem() { Text = "8D" },
                    new SelectListItem() { Text = "8E" },
                    new SelectListItem() { Text = "8F" },
                    new SelectListItem() { Text = "9A" },
                    new SelectListItem() { Text = "9B" },
                    new SelectListItem() { Text = "9C" },
                    new SelectListItem() { Text = "9D" },
                    new SelectListItem() { Text = "9E" },
                    new SelectListItem() { Text = "9F" },
                    }), "Chọn lớp", new { @class = "form-control" })

        @Html.DropDownList("SearchObject", (IEnumerable<SelectListItem>
                   )(new[] {
                   new SelectListItem() { Text = "None" },
                   new SelectListItem() { Text = "10%" },
                   new SelectListItem() { Text = "20%" },
                   new SelectListItem() { Text = "25%" },
                   new SelectListItem() { Text = "30%" },
                   new SelectListItem() { Text = "40%" },
                   new SelectListItem() { Text = "50%" },
                   new SelectListItem() { Text = "60%" },
                   new SelectListItem() { Text = "70%" },
                   new SelectListItem() { Text = "75%" },
                   new SelectListItem() { Text = "80%" },
                   new SelectListItem() { Text = "90%" },
                   new SelectListItem() { Text = "100%" },
                   }), "chọn đối tượng", new { @class = "form-control" })

        @Html.DropDownList("SearchStatus", (IEnumerable<SelectListItem>
                   )(new[] {
                   new SelectListItem() { Text = "Đã đóng" },
                   new SelectListItem() { Text = "Chưa đóng" },
                   }), "Chọn trạng thái", new { @class = "form-control" })
        <input type="submit" class="btn btn-default" value="Tìm kiếm" />
        <a  class="btn btn-default" href="~/Danhsachsinhvien/index" >Tất cả sinh viên</a>
    </div>
}
<table class="table">
    <tr>
        <th>
            Tên học viên
        </th>
        <th>
            Lớp
        </th>
        <th>
            Khóa/Khối
        </th>
        <th>
            Đối tượng
        </th>
        <th>
            Số điện thoại
        </th>
        <th>
            Ngày nhập học
        </th>
        <th>
            Học Phí
        </th>
        <th>
            Trạng thái
        </th>
        <th>
            Thực thu
        </th>
        <th>
            Ngày thu
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tenhocvien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lop)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.khoa_khoi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.doituong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sdt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ngaynhaphoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hocphi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.trangthai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.thucthu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ngaythu)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.mahocvien }) |
                @Html.ActionLink("Thu học phí", "Status", new { id = item.mahocvien }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.mahocvien }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.mahocvien }) |

            </td>
        </tr>
    }

</table>

Project LMS/Views/Danhsachsinhvien/Status.cshtml
@model Project_LMS.Models.Danh_sách_sinh_viên

@{
    ViewBag.Title = "Thu học phí";
}

<h2>Thu tiền học phí</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Thông tin thu tiền</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.mahocvien)
   
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.tenhocvien)
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.lop)
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.khoa_khoi)
   
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.doituong)
   
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.sdt)
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ngaynhaphoc)
    
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.hocphi)

    <div class="form-group">
        @Html.LabelFor(model => model.trangthai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.trangthai, (IEnumerable<SelectListItem>
                    )(new[] {
                    new SelectListItem() { Text = "Đã đóng" },
                    new SelectListItem() { Text = "Chưa đóng" },
                    }), "Chọn trạng thái", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.trangthai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.thucthu, "Thực thu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.thucthu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.thucthu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ngaythu, "Ngày thu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ngaythu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ngaythu, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay về", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}