Project LMS/Models/Danh_sách_giáo_viên.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danh_sách_giáo_viên
    {
        public string Magiangvien { get; set; }
        public string Hovaten { get; set; }
        public string Mangach { get; set; }
        public string Chucvu { get; set; }
        public string Tobomon { get; set; }
        public string Loaihopdong { get; set; }
        public Nullable<System.DateTime> Ngayvaotruong { get; set; }
        public string Nghiphep { get; set; }
        public string Trangthai { get; set; }
        public string Gioitinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public Nullable<int> SoCMND { get; set; }
        public Nullable<System.DateTime> Ngaycap { get; set; }
        public string Noicap { get; set; }
        public string Diachi { get; set; }
        public string SoBHXH { get; set; }
        public string Trinhdodaotao { get; set; }
        public Nullable<System.DateTime> Ngayapdungchucvu { get; set; }
        public Nullable<System.DateTime> Ngaybatdaulamviec { get; set; }
        public string Ngach_hang { get; set; }
        public string Bacluong { get; set; }
        public string Hesoluong { get; set; }
        public Nullable<System.DateTime> Ngayapdungngachbac { get; set; }
        public string Phucap { get; set; }
        public Nullable<int> Luongcoban { get; set; }
    }
}

Project LMS/Controllers/Danh_sách_giáo_viênController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_LMS.Models;

namespace Project_LMS.Controllers
{
    public class Danh_sách_giáo_viênController : Controller
    {
        private LMSEntities db = new LMSEntities();

        // GET: Danh_sách_giáo_viên
        public ActionResult Index(string SearchString = "", string Searchtobomon = "", string Searchloaihopdong = "", string Searchtrangthai = "")
        {
            //return View(db.Danh_sách_giáo_viên.ToList());
            var dsgiaovien = from x in db.Danh_sách_giáo_viên select x;
            if (SearchString != "")
            {
                dsgiaovien = dsgiaovien.Where(x => x.Hovaten.Contains(SearchString));
            }
            if (Searchtobomon != "")
            {
                dsgiaovien = dsgiaovien.Where(x => x.Tobomon.Contains(Searchtobomon));
            }
            if (Searchloaihopdong != "")
            {
                dsgiaovien = dsgiaovien.Where(x => x.Loaihopdong.Contains(Searchloaihopdong));
            }
            if (Searchtrangthai != "")
            {
                dsgiaovien = dsgiaovien.Where(x => x.Trangthai.Contains(Searchtrangthai));
            }
            return View(dsgiaovien.ToList());
        }

        // GET: Danh_sách_giáo_viên/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Danh_sách_giáo_viên danh_sách_giáo_viên = db.Danh_sách_giáo_viên.Find(id);
            if (danh_sách_giáo_viên == null)
            {
                return HttpNotFound();
            }
            return View(danh_sách_giáo_viên);
        }

        // GET: Danh_sách_giáo_viên/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Danh_sách_giáo_viên/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Magiangvien,Hovaten,Mangach,Chucvu,Tobomon,Loaihopdong,Ngayvaotruong,Nghiphep,Trangthai,Gioitinh,Ngaysinh,SoCMND,Ngaycap,Noicap,Diachi,SoBHXH,Trinhdodaotao,Ngayapdungchucvu,Ngaybatdaulamviec,Ngach_hang,Bacluong,Hesoluong,Ngayapdungngachbac,Phucap,Luongcoban")] Danh_sách_giáo_viên danh_sách_giáo_viên)
        {
            if (ModelState.IsValid)
            {
                db.Danh_sách_giáo_viên.Add(danh_sách_giáo_viên);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(danh_sách_giáo_viên);
        }

        // GET: Danh_sách_giáo_viên/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Danh_sách_giáo_viên danh_sách_giáo_viên = db.Danh_sách_giáo_viên.Find(id);
            if (danh_sách_giáo_viên == null)
            {
                return HttpNotFound();
            }
            return View(danh_sách_giáo_viên);
        }

        // POST: Danh_sách_giáo_viên/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Magiangvien,Hovaten,Mangach,Chucvu,Tobomon,Loaihopdong,Ngayvaotruong,Nghiphep,Trangthai,Gioitinh,Ngaysinh,SoCMND,Ngaycap,Noicap,Diachi,SoBHXH,Trinhdodaotao,Ngayapdungchucvu,Ngaybatdaulamviec,Ngach_hang,Bacluong,Hesoluong,Ngayapdungngachbac,Phucap,Luongcoban")] Danh_sách_giáo_viên danh_sách_giáo_viên)
        {
            if (ModelState.IsValid)
            {
                db.Entry(danh_sách_giáo_viên).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(danh_sách_giáo_viên);
        }

        // GET: Danh_sách_giáo_viên/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Danh_sách_giáo_viên danh_sách_giáo_viên = db.Danh_sách_giáo_viên.Find(id);
            if (danh_sách_giáo_viên == null)
            {
                return HttpNotFound();
            }
            return View(danh_sách_giáo_viên);
        }

        // POST: Danh_sách_giáo_viên/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Danh_sách_giáo_viên danh_sách_giáo_viên = db.Danh_sách_giáo_viên.Find(id);
            db.Danh_sách_giáo_viên.Remove(danh_sách_giáo_viên);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project LMS/Views/Danh_sách_giáo_viên/Create.cshtml
@model Project_LMS.Models.Danh_sách_giáo_viên

@{
    ViewBag.Title = "Create";
}
<link href="@Url.Content("~/Content/StyleSheet1.css")" rel="stylesheet" type="text/css" />

<h2>Thêm giảng viên</h2>


@using (Html.BeginForm())  
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Thông tin giảng viên</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="infor-teacher">
    <div class="left">
        <div class="form-group">
            @Html.LabelFor(model => model.Magiangvien, "Mã giáo viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Magiangvien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Magiangvien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hovaten, " Họ và tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hovaten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hovaten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gioitinh, "Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Gioitinh, (IEnumerable<SelectListItem>
                   )(new[] {
                   new SelectListItem() { Text = "Nam" },
                   new SelectListItem() { Text = "Nữ" },
                   }), "Chọn giới tính", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gioitinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngaysinh, "Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngaysinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngaysinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoCMND, "CMND/CCCD", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoCMND, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoCMND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngaycap, "Ngày cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngaycap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngaycap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Noicap, "Nơi cấp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Noicap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Noicap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Diachi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Diachi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diachi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Ngayvaotruong, "Ngày vào trường", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngayvaotruong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngayvaotruong, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="right">
        <div class="form-group">
            @Html.LabelFor(model => model.SoBHXH, "Số sổ BHXH", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoBHXH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoBHXH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Trinhdodaotao, "Trình độ đào tạo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Trinhdodaotao, (IEnumerable<SelectListItem>
                  )(new[] {
                  new SelectListItem() { Text = "Đại học" },
                  new SelectListItem() { Text = "Cao đẳng" },
                  }), "Chọn Trình độ đào tạo", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Trinhdodaotao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chucvu, "Chức vụ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Chucvu, (IEnumerable<SelectListItem>
                  )(new[] {
                  new SelectListItem() { Text = "Giảng viên" },
                  new SelectListItem() { Text = "Trưởng bộ môn" },
                  new SelectListItem() { Text = "Trưởng Khoa" },
                  new SelectListItem() { Text = "Phó khoa" },
                  }), "Chọn chức vụ", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Chucvu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tobomon, "Tổ bộ môn", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Tobomon, (IEnumerable<SelectListItem>
                   )(new[] {
                   new SelectListItem() { Text = "Khoa học máy tính" },
                   new SelectListItem() { Text = "Toán - Tin" },
                   new SelectListItem() { Text = "Kinh tế - Chính trị" },
                   }), "Chọn tổ bộ môn", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tobomon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngayapdungchucvu, "Ngày áp dụng chức vụ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngayapdungchucvu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngayapdungchucvu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngaybatdaulamviec, "Ngày bắt đầu làm việc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngaybatdaulamviec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngaybatdaulamviec, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Trangthai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Trangthai, (IEnumerable<SelectListItem>
                  )(new[] {
                  new SelectListItem() { Text = "Sắp giảng dạy" },
                  new SelectListItem() { Text = "Đang giảng dạy" },
                  new SelectListItem() { Text = "Ngừng giảng dạy" },
                  }), "Chọn Trạng thái", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Trangthai, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
   </div>
        <h4>Thông tin lương</h4>
 

    <div class="form-group">
        @Html.LabelFor(model => model.Loaihopdong, "Loại hợp đồng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Loaihopdong, (IEnumerable<SelectListItem>
                  )(new[] {
                  new SelectListItem() { Text = "Hợp đồng thử việc" },
                  new SelectListItem() { Text = "Biên chế" },
                  }), "Chọn Loại hợp đồng", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Loaihopdong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Luongcoban, "Lương cơ bản", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Luongcoban, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Luongcoban, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ngach_hang, "Ngạch hạng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ngach_hang, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ngach_hang, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Mangach, "Mã ngạch", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mangach, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mangach, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bacluong, "Bậc lương", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Bacluong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Bacluong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Hesoluong, "Hệ số lương", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Hesoluong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Hesoluong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ngayapdungngachbac, "Ngày áp dụng ngạch bậc", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ngayapdungngachbac, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ngayapdungngachbac, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phucap, "Phụ cấp", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phucap, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phucap, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project LMS/Views/Danh_sách_giáo_viên/Delete.cshtml
@model Project_LMS.Models.Danh_sách_giáo_viên

@{
    ViewBag.Title = "Delete";
}

<h2>Danh sách giáo viên</h2>

<h3>Bạn có muốn xóa giáo viên</h3>
<div>
    <h4>Thông tin giáo viên</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Họ và tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hovaten)
        </dd>

        <dt>
            Mã ngạch
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mangach)
        </dd>

        <dt>
            Chức vụ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chucvu)
        </dd>

        <dt>
            Tổ bộ môn
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tobomon)
        </dd>

        <dt>
            Loại hợp đồng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Loaihopdong)
        </dd>

        <dt>
            Ngày vào trường
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngayvaotruong)
        </dd>

        <dt>
            Nghỉ phép
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nghiphep)
        </dd>

        <dt>
            Trạng thái
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trangthai)
        </dd>

        <dt>
            Giới tính
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gioitinh)
        </dd>

        <dt>
            Ngày sinh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngaysinh)
        </dd>

        <dt>
            Số CMND
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoCMND)
        </dd>

        <dt>
            Ngày cấp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngaycap)
        </dd>

        <dt>
            Nơi cấp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Noicap)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diachi)
        </dd>

        <dt>
            Số BHXH
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoBHXH)
        </dd>

        <dt>
            Trình độ đào tạo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trinhdodaotao)
        </dd>

        <dt>
            Ngày áp dụng chức vụ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngayapdungchucvu)
        </dd>

        <dt>
            Ngày bắt đầu làm việc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngaybatdaulamviec)
        </dd>

        <dt>
            Ngạch / hạng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngach_hang)
        </dd>

        <dt>
            Bậc lương
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bacluong)
        </dd>

        <dt>
            Hệ số lương
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hesoluong)
        </dd>

        <dt>
            Ngày áp dụng ngạch bậc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngayapdungngachbac)
        </dd>

        <dt>
            Phụ cấp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phucap)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay về", "Index")
        </div>
    }
</div>

Project LMS/Views/Danh_sách_giáo_viên/Index.cshtml
@model IEnumerable<Project_LMS.Models.Danh_sách_giáo_viên>

@{
    ViewBag.Title = "Index";
}

<h2>Danh sách giảng viên</h2>

<p>
    @Html.ActionLink("Thêm giảng viên mới", "Create")
</p>

@using (Html.BeginForm("Index", "Danh_sách_giáo_viên", FormMethod.Post))
{
    <div class="form-group form-inline">
        <input type="text" name="SearchString" placeholder="Nhập tên giáo viên" class="form-control" />
        @Html.DropDownList("Searchtobomon", (IEnumerable<SelectListItem>)
                (new[] {
                 new SelectListItem() { Text = "Khoa học máy tính" },
                 new SelectListItem() { Text = "Toán - Tin" },
                 new SelectListItem() { Text = "Kinh tế - Chính trị" },
                }), "Chọn Tổ bộ môn", new { @class = "form-control" })

        @Html.DropDownList("Searchloaihopdong", (IEnumerable<SelectListItem>
                     )(new[] {
                     new SelectListItem() { Text = "Hợp đồng thử việc" },
                     new SelectListItem() { Text = "Biên chế" },
                }), "Chọn loại hợp đồng", new { @class = "form-control" })


        @Html.DropDownList("Searchtrangthai", (IEnumerable<SelectListItem>
                    )(new[] {
                  new SelectListItem() { Text = "Sắp giảng dạy" },
                  new SelectListItem() { Text = "Đang giảng dạy" },
                  new SelectListItem() { Text = "Ngừng giảng dạy" },
                    }), "Chọn trạng thái", new { @class = "form-control" })
        
        <input type="submit" class="btn btn-default" value="Tìm kiếm" />
        <a class="btn btn-default" href="~/Danh_sách_giáo_viên/index">Tất cả giáo viên</a>
    </div>
}

<table class="table">
    <tr>
        <th>
            Mã giảng viên
        </th>
        <th>
            Họ và tên
        </th>
        <th>
            Mã ngạch
        </th>
        <th>
            Chức vụ
        </th>
        <th>
            Tổ bộ môn
        </th>
        <th>
            Loại hợp đồng
        </th>
        <th>
            Ngày vào trường
        </th>
        <th>
            Nghỉ phép
        </th>
        <th>
            Trạng thái
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Magiangvien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hovaten)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mangach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Chucvu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tobomon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Loaihopdong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ngayvaotruong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nghiphep)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Trangthai)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.Magiangvien }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.Magiangvien }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.Magiangvien })
            </td>
        </tr>
    }

</table>