Project LMS/Controllers/DanhsachmonhocController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_LMS.Models;

namespace Project_LMS.Controllers
{
    public class DanhsachmonhocController : Controller
    {
        private LMSEntities db = new LMSEntities();

        // GET: Danhsachmonhoc
       
        public ActionResult Index(string SearchString = "", string searchGrade = "",
            string SearchSubject = "", string searchStatus = "", string searchYear = "")
        {
            var dsmonhoc = from x in db.Danh_sách_môn_học select x;
            if (SearchString != "")
            {
                dsmonhoc = dsmonhoc.Where(x => x.Monhoc.Contains(SearchString));
            }
            if (SearchSubject != "")
            {
                dsmonhoc = dsmonhoc.Where(x => x.Monhoc.Contains(SearchSubject));
            }
            if (searchStatus != "")
            {
                dsmonhoc = dsmonhoc.Where(x => x.Trangthai.Contains(searchStatus));
            }
            if (searchGrade != "")
            {
                dsmonhoc = dsmonhoc.Where(x => x.Khoa_khoi.Contains(searchGrade));
            }
            if (searchYear != "")
            {
                dsmonhoc = dsmonhoc.Where(x => x.Nienkhoa1.Contains(searchYear));
            }
            return View(dsmonhoc.ToList());
        }

        // GET: Danhsachmonhoc/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Danh_sách_môn_học danh_sách_môn_học = db.Danh_sách_môn_học.Find(id);
            if (danh_sách_môn_học == null)
            {
                return HttpNotFound();
            }
            return View(danh_sách_môn_học);
        }

        // GET: Danhsachmonhoc/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Danhsachmonhoc/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Mamonhoc,Monhoc,Khoa_khoi,Donvitinh,Trangthai,Tonghocphi,Mucthumoidonvi,Nienkhoa,Thoiluong,Thoiluongmonhoc,Tonghocphiphaithu,Nienkhoa1")] Danh_sách_môn_học danh_sách_môn_học)
        {
            if (ModelState.IsValid)
            {
                danh_sách_môn_học.Tonghocphiphaithu = danh_sách_môn_học.Thoiluongmonhoc * danh_sách_môn_học.Mucthumoidonvi;
                db.Danh_sách_môn_học.Add(danh_sách_môn_học);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(danh_sách_môn_học);
        }

        // GET: Danhsachmonhoc/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Danh_sách_môn_học danh_sách_môn_học = db.Danh_sách_môn_học.Find(id);
            if (danh_sách_môn_học == null)
            {
                return HttpNotFound();
            }
            return View(danh_sách_môn_học);
        }

        // POST: Danhsachmonhoc/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Mamonhoc,Monhoc,Khoa_khoi,Donvitinh,Trangthai,Tonghocphi,Mucthumoidonvi,Nienkhoa,Thoiluong,Thoiluongmonhoc,Tonghocphiphaithu,Nienkhoa1")] Danh_sách_môn_học danh_sách_môn_học)
        {
            if (ModelState.IsValid)
            {
                danh_sách_môn_học.Tonghocphiphaithu = danh_sách_môn_học.Thoiluongmonhoc * danh_sách_môn_học.Mucthumoidonvi;
                db.Entry(danh_sách_môn_học).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(danh_sách_môn_học);
        }

        // GET: Danhsachmonhoc/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Danh_sách_môn_học danh_sách_môn_học = db.Danh_sách_môn_học.Find(id);
            if (danh_sách_môn_học == null)
            {
                return HttpNotFound();
            }
            return View(danh_sách_môn_học);
        }

        // POST: Danhsachmonhoc/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Danh_sách_môn_học danh_sách_môn_học = db.Danh_sách_môn_học.Find(id);
            db.Danh_sách_môn_học.Remove(danh_sách_môn_học);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project LMS/Views/Danhsachmonhoc/Create.cshtml
@model Project_LMS.Models.Danh_sách_môn_học

@{
    ViewBag.Title = "Create";
}

<h2>Danh sách môn học</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Thêm môn học</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Mamonhoc, "Mã môn học", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mamonhoc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mamonhoc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Monhoc, "Môn học", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Monhoc, (IEnumerable<SelectListItem>
                )(new[] {
                    new SelectListItem() { Text = "Pháp luật" },
                    new SelectListItem() { Text = "Chính trị" },
                    new SelectListItem() { Text = "Huấn luyện quân sự và an ninh" },
                    new SelectListItem() { Text = "làm việc nhóm" },
                    new SelectListItem() { Text = "Lập trình thủ tục" },
                    new SelectListItem() { Text = "Networking" },
                    new SelectListItem() { Text = "Lập trình" },
                    new SelectListItem() { Text = "Cơ bản về CNTT" },
                    new SelectListItem() { Text = "Giao tiếp kinh doanh" },
                    new SelectListItem() { Text = "Thiết kế & Phát triển cơ sở dữ liệu" },
                    new SelectListItem() { Text = "An ninh mạng" },
                    new SelectListItem() { Text = "Vòng đời phát triển phần mềm" },
                    new SelectListItem() { Text = "Thiết kế & phát triển trang web" },
                    new SelectListItem() { Text = "Thực hành nghề nghiệp" },
                    new SelectListItem() { Text = "Cấu trúc dữ liệu & thuật toán" },
                    new SelectListItem() { Text = "Quản lý một dự án điện toán" },
                    new SelectListItem() { Text = "Kĩ năng thương lượng" },
                    new SelectListItem() { Text = "Internet of Things" },
                    new SelectListItem() { Text = "Kỹ năng quản lý" },
                    new SelectListItem() { Text = "Điện toán đám mây" },
                    new SelectListItem() { Text = "Lập trình nâng cao" },
                    new SelectListItem() { Text = "Phát triển ứng ụng" },
                    new SelectListItem() { Text = "Kinh doanh thônng ming" },
                    new SelectListItem() { Text = "Dự án nghiên cứu máy tính" },
                }), "Chọn Môn học", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Monhoc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Khoa_khoi, "Khoa / Khối", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Khoa_khoi, (IEnumerable<SelectListItem>
                 )(new[] {
                 new SelectListItem() { Text = "Khối 6" },
                 new SelectListItem() { Text = "Khối 7" },
                 new SelectListItem() { Text = "Khối 8" },
                 new SelectListItem() { Text = "Khối 9" },
                 }), "chọn khoa / Khối", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Khoa_khoi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tonghocphiphaithu, "Tổng học phí phải thu", htmlAttributes: new { @class = "control-label col-md-2" })
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thoiluongmonhoc, "Thời lượng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Thoiluongmonhoc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Thoiluongmonhoc, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tonghocphi, "Đơn vị tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Tonghocphi, (IEnumerable<SelectListItem>
                    )(new[] {
                    new SelectListItem() { Text = "Tín chỉ" },
                    new SelectListItem() { Text = "Tiết học" },
                    }), "Chọn đơn vị tính", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tonghocphi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mucthumoidonvi, "Mức thu / 1 đơn vị tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mucthumoidonvi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mucthumoidonvi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Trangthai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Trangthai, (IEnumerable<SelectListItem>
                    )(new[] {
                    new SelectListItem() { Text = "Chưa áp dụng" },
                    new SelectListItem() { Text = "Đang áp dụng" },
                    new SelectListItem() { Text = "Ngừng áp dụng" },
                    }), "Chọn trạng thái", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Trangthai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nienkhoa1, "Niên khóa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Nienkhoa1, (IEnumerable<SelectListItem>
                    )(new[] {
                    new SelectListItem() { Text = "2019 - 2020" },
                    new SelectListItem() { Text = "2020 - 2021" },
                    new SelectListItem() { Text = "2021 - 2022" },
                    }), "Chọn niên khóa", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nienkhoa1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        <a class="btn btn-default" href="~/Danhsachmonhoc/Index">Quay lại</a>
    </div>

Project LMS/Views/Danhsachmonhoc/Delete.cshtml
@model Project_LMS.Models.Danh_sách_môn_học

@{
    ViewBag.Title = "Delete";
}

<h2>Danh sách môn học</h2>

<h3>Bạn có chắc chắn xóa môn học này không?</h3>
<div>
    <h4>Thông tin môn học</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monhoc)
        </dd>

        <dt>
            Khóa / Khối
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Khoa_khoi)
        </dd>

        <dt>
            Đơn vị tính
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tonghocphi)
        </dd>

        <dt>
            Trạng thái
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trangthai)
        </dd>

        <dt>
            Tổng học phí phải thu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tonghocphiphaithu)
        </dd>

        <dt>
            Mức thu / 1 đơn vị tính
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mucthumoidonvi)
        </dd>

        <dt>
            Niên khóa
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nienkhoa1)
        </dd>

        <dt>
            Thời lượng môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thoiluongmonhoc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            <a class="btn btn-default" href="~/Danhsachmonhoc/Index" >Quay lại</a>
        </div>
    }
</div>

Project LMS/Views/Danhsachmonhoc/Details.cshtml
@model Project_LMS.Models.Danh_sách_môn_học

@{
    ViewBag.Title = "Details";
}

<h2>Danh sách môn học</h2>

<div>
    <h4>Thông tin chi tiết môn học</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monhoc)
        </dd>

        <dt>
            Khoa / khối
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Khoa_khoi)
        </dd>

        <dt>
            Đơn vị tính
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tonghocphi)
        </dd>

        <dt>
            Trạng thái
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trangthai)
        </dd>

        <dt>
            Tổng học phí phải thu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tonghocphiphaithu)
        </dd>

        <dt>
            Mức thu / 1 đơn vị tính
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mucthumoidonvi)
        </dd>

        <dt>
            Niên khóa
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nienkhoa1)
        </dd>

        <dt>
            Thời lượng môn học
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thoiluongmonhoc)
        </dd>

    </dl>
</div>
<p>
    <a class="btn btn-default" @Html.ActionLink("Cập nhật", "Edit", new { id = Model.Mamonhoc }) | </a>
    <a class="btn btn-default" href="~/Danhsachmonhoc/Index">Quay lại</a>
</p>

Project LMS/Views/Danhsachmonhoc/Edit.cshtml
@model Project_LMS.Models.Danh_sách_môn_học

@{
    ViewBag.Title = "Edit";
}

<h2>Danh sách môn học</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Cập nhật thông tin môn học</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Mamonhoc)

    <div class="form-group">
        @Html.LabelFor(model => model.Monhoc, "Môn học", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Monhoc, (IEnumerable<SelectListItem>
                )(new[] {
                    new SelectListItem() { Text = "Pháp luật" },
                    new SelectListItem() { Text = "Chính trị" },
                    new SelectListItem() { Text = "Huấn luyện quân sự và an ninh" },
                    new SelectListItem() { Text = "làm việc nhóm" },
                    new SelectListItem() { Text = "Lập trình thủ tục" },
                    new SelectListItem() { Text = "Networking" },
                    new SelectListItem() { Text = "Lập trình" },
                    new SelectListItem() { Text = "Cơ bản về CNTT" },
                    new SelectListItem() { Text = "Giao tiếp kinh doanh" },
                    new SelectListItem() { Text = "Thiết kế & Phát triển cơ sở dữ liệu" },
                    new SelectListItem() { Text = "An ninh mạng" },
                    new SelectListItem() { Text = "Vòng đời phát triển phần mềm" },
                    new SelectListItem() { Text = "Thiết kế & phát triển trang web" },
                    new SelectListItem() { Text = "Thực hành nghề nghiệp" },
                    new SelectListItem() { Text = "Cấu trúc dữ liệu & thuật toán" },
                    new SelectListItem() { Text = "Quản lý một dự án điện toán" },
                    new SelectListItem() { Text = "Kĩ năng thương lượng" },
                    new SelectListItem() { Text = "Internet of Things" },
                    new SelectListItem() { Text = "Kỹ năng quản lý" },
                    new SelectListItem() { Text = "Điện toán đám mây" },
                    new SelectListItem() { Text = "Lập trình nâng cao" },
                    new SelectListItem() { Text = "Phát triển ứng ụng" },
                    new SelectListItem() { Text = "Kinh doanh thônng ming" },
                    new SelectListItem() { Text = "Dự án nghiên cứu máy tính" },
                }), "Chọn Môn học", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Monhoc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Khoa_khoi, "Khoa / Khối", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Khoa_khoi, (IEnumerable<SelectListItem>
                 )(new[] {
                 new SelectListItem() { Text = "Khối 6" },
                 new SelectListItem() { Text = "Khối 7" },
                 new SelectListItem() { Text = "Khối 8" },
                 new SelectListItem() { Text = "Khối 9" },
                 }), "chọn khoa / Khối", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Khoa_khoi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Thoiluongmonhoc, "Thời lượng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Thoiluongmonhoc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Thoiluongmonhoc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tonghocphi, "Đơn vị tính", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tonghocphi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tonghocphi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mucthumoidonvi, "Mức thu / 1 đơn vị tính", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mucthumoidonvi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mucthumoidonvi, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Trangthai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Trangthai, (IEnumerable<SelectListItem>
                )(new[] {
                new SelectListItem() { Text = "Chưa áp dụng" },
                new SelectListItem() { Text = "Đang áp dụng" },
                new SelectListItem() { Text = "Ngừng áp dụng" },
                }), "Chọn trạng thái", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Trangthai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nienkhoa1, "Niên khóa", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Nienkhoa1, (IEnumerable<SelectListItem>
                )(new[] {
                new SelectListItem() { Text = "2019 - 2020" },
                new SelectListItem() { Text = "2020 - 2021" },
                new SelectListItem() { Text = "2021 - 2022" },
                }), "Chọn niên khóa", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Nienkhoa1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    <a class="btn btn-default" href="~/Danhsachmonhoc/Index">Quay lại</a>
</div>

Project LMS/Views/Danhsachmonhoc/Index.cshtml
@model IEnumerable<Project_LMS.Models.Danh_sách_môn_học>

@{
    ViewBag.Title = "Index";
}

<h2>Danh sách môn học</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
@using (Html.BeginForm("Index", "Danhsachmonhoc", FormMethod.Post))
{
    <div class="form-group form-inline">
        <input type="text" name="SearchString" placeholder="Nhập tên môn học" class="form-control" />
        @Html.DropDownList("SearchGrade", (IEnumerable<SelectListItem>)
                (new[] {
               new SelectListItem() { Text = "Khối 6" },
               new SelectListItem() { Text = "Khối 7" },
               new SelectListItem() { Text = "Khối 8" },
               new SelectListItem() { Text = "Khối 9" },
                }), "Chọn khoa / khối", new { @class = "form-control" })

        @Html.DropDownList("SearchSubject", (IEnumerable<SelectListItem>
                     )(new[] {
                    new SelectListItem() { Text = "Pháp luật" },
                    new SelectListItem() { Text = "Chính trị" },
                    new SelectListItem() { Text = "Huấn luyện quân sự và an ninh" },
                    new SelectListItem() { Text = "làm việc nhóm" },
                    new SelectListItem() { Text = "Lập trình thủ tục" },
                    new SelectListItem() { Text = "Networking" },
                    new SelectListItem() { Text = "Lập trình" },
                    new SelectListItem() { Text = "Cơ bản về CNTT" },
                    new SelectListItem() { Text = "Giao tiếp kinh doanh" },
                    new SelectListItem() { Text = "Thiết kế & Phát triển cơ sở dữ liệu" },
                    new SelectListItem() { Text = "An ninh mạng" },
                    new SelectListItem() { Text = "Vòng đời phát triển phần mềm" },
                    new SelectListItem() { Text = "Thiết kế & phát triển trang web" },
                    new SelectListItem() { Text = "Thực hành nghề nghiệp" },
                    new SelectListItem() { Text = "Cấu trúc dữ liệu & thuật toán" },
                    new SelectListItem() { Text = "Quản lý một dự án điện toán" },
                    new SelectListItem() { Text = "Kĩ năng thương lượng" },
                    new SelectListItem() { Text = "Internet of Things" },
                    new SelectListItem() { Text = "Kỹ năng quản lý" },
                    new SelectListItem() { Text = "Điện toán đám mây" },
                    new SelectListItem() { Text = "Lập trình nâng cao" },
                    new SelectListItem() { Text = "Phát triển ứng ụng" },
                    new SelectListItem() { Text = "Kinh doanh thônng ming" },
                    new SelectListItem() { Text = "Dự án nghiên cứu máy tính" },
                }), "Chọn Môn học", new { @class = "form-control" })


        @Html.DropDownList("SearchStatus", (IEnumerable<SelectListItem>
                    )(new[] {
                   new SelectListItem() { Text = "Chưa áp dụng" },
                   new SelectListItem() { Text = "Đang áp dụng" },
                   new SelectListItem() { Text = "Ngừng áp dụng" },
                    }), "Chọn trạng thái", new { @class = "form-control" })
        @Html.DropDownList("searchYear", (IEnumerable<SelectListItem>
                    )(new[] {
                    new SelectListItem() { Text = "2019 - 2020" },
                    new SelectListItem() { Text = "2020 - 2021" },
                    new SelectListItem() { Text = "2021 - 2022" },
                    }), "Chọn niên khóa", new { @class = "form-control" })
        <input type="submit" class="btn btn-default" value="Tìm kiếm" />
        <a class="btn btn-default" href="~/Danhsachmonhoc/index">Tất cả Môn học</a>
    </div>
}
    <table class="table">
        <tr>
            <th>
                Mã môn học
            </th>
            <th>
                Môn học
            </th>
            <th>
                Khoa / Khối
            </th>
            <th>
                Thời lượng
            </th>
            <th>
                Đơn vị tính
            </th>
            <th>
                Mức thu / 1 đơn vị tính
            </th>
            <th>
                Tổng học phí
            </th>
            <th>
                Trạng thái
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Mamonhoc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Monhoc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Khoa_khoi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Thoiluongmonhoc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tonghocphi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mucthumoidonvi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tonghocphiphaithu)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Trangthai)
                </td>
                <td>
                    @Html.ActionLink("Cập nhật", "Edit", new { id = item.Mamonhoc }) |
                    @Html.ActionLink("Thông tin chi tiết", "Details", new { id = item.Mamonhoc }) |
                    @Html.ActionLink("Xóa", "Delete", new { id = item.Mamonhoc })
                </td>
            </tr>
        }

    </table>